### ISSUE TITLE
Deprecated: Required parameter $managerRegistry

### ISSUE THREAD

**Issue by art-cg** [metaclass-nl/filter-bundle#1]
Hi, i just noticed a deprecation in Symfony 5.3 and Php 8.0.7
Deprecated: Required parameter $managerRegistry follows optional parameter $classExp in \api\vendor\metaclass-nl\filter-bundle\src\Filter\FilterLogic.php on line 40

Possible Solution:
Move ManagerRegistry $managerRegistry to first or third position in Constructor.

**Comment by metaclass-nl** [comment]
Thanks for reporting this. Solved in commit 0c9bfb9

**Comment by art-cg** [comment]
Thanks
