### ISSUE TITLE
Please release 523ba16b07

### ISSUE THREAD

**Issue by smindel** [metaclass-nl/filter-bundle#6]
Hi,
I'd love to give your module a go. Unfortunately my project locks symfony/orm to version 2.7 and metaclass-nl/filter-bundle requires ^2.8. Could you please release 523ba16b07 ?
Cheers
Andy

**Comment by metaclass-nl** [comment]
Hi Andy,

AFAIK that version has not been tested with doctrine/orm 2.0. But maybe you did run the unit tests with 2.7? (Unit tests are in metaclass-nl/test-filter-bundle).

If not i will look into it later this week.

Greetings, Henk.

**Comment by metaclass-nl** [comment]
require-dev of Api Platform Core  defines "doctrine/orm": "^2.6.4" so i tried to run the tests with that, but had so many problems getting an installable and working combination with symfony that i ended up with ^2.7 and symfony 5.3. But then it worked, so i merged it, you should now be able to install it with 2.7.
